[project]
name = "career-intelligence"
version = "0.1.0"
description = "assuming 3.14 is too cutting edge"
readme = "README.md"
requires-python = ">=3.13.11,<3.14"
dependencies = [
    "rio-ui>=0.12",
]
